name: React CI/CD

on:
  push:
    branches: [ "dev", "uat", "prod" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: npm ci

      - name: Build React app
        run: npm run build

      # Deploy to DEV
      - name: Deploy to DEV
        if: github.ref == 'refs/heads/dev'
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USER }}
          key: ${{ secrets.DEV_SSH_KEY }}
          source: "build/*"
          target: "/var/www/reactapp"

      # Deploy to UAT
      - name: Deploy to UAT
        if: github.ref == 'refs/heads/uat'
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.UAT_HOST }}
          username: ${{ secrets.UAT_USER }}
          key: ${{ secrets.UAT_SSH_KEY }}
          source: "build/*"
          target: "/var/www/reactapp"

      # Deploy to PROD
      - name: Deploy to PROD
        if: github.ref == 'refs/heads/prod'
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          source: "build/*"
          target: "/var/www/reactapp"
